version: '3.9'
services:

  registry:
    container_name: registry-ctn
    image: registry
    ports:
      - 5000:5000
    volumes:
      - /path/data:/var/lib/registry

  registry-front:
    image: joxit/docker-registry-ui:1.5-static
    ports:
      - 8080:80
    environment:
      - REGISTRY_TITLE=3DOKR 4DOKR Registry
      - REGISTRY_URL=http://registry-ctn:5000
    depends_on:
      - registry

# https://hub.docker.com/_/registry
# https://hub.docker.com/r/joxit/docker-registry-ui 