version: "3.9"
services:

  website:
    container_name: website
    image: php:apache
    ports:
      - "80:80"
    volumes:
      - ./website:/var/www/html
    env_file:
      - .env
    depends_on:
      - simple_api

  simple_api:
    container_name: simple_api
    build:
      context: ./simple_api
      dockerfile: Dockerfile
    ports:
      - 5000:5000